<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyAccounting.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Popforge.Shared\packages\dotnet\Popforge.AspNetCore.Extensions\Popforge.AspNetCore.Extensions.csproj" />
  </ItemGroup>

</Project>
